version: '3.7'

services:
  back:
    restart: unless-stopped
    build:
      context: ./back
      target: development
      args:
        NODE_ENV: ${ENVIRONMENT}
    volumes:
      - /usr/src/back/node_modules
      - ./back:/usr/src/back
    environment:
      NODE_ENV: ${ENVIRONMENT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_HOST: ${SQL_HOST}
      DATABASE_PORT: ${SQL_PORT}
      DATABASE_NAME: ${SQL_DATABASE}
      DATABASE_USERNAME: ${SQL_USER}
      DATABASE_PASSWORD: ${SQL_PASSWORD}
    ports:
      - 39002:39002
    depends_on:
      - sql

  sql:
    restart: unless-stopped
    image: mariadb:10.2.38-bionic
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SQL_DATABASE}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:5.1
    links:
      - sql:db
    ports:
      - 39003:80
    depends_on:
      - sql